### PR TITLE
chore: update dev instructions to use pnpm

### PR DESCRIPTION
**Pull request by IonianPlayboy**
A possible fix for #19, alternative to #21

If that's the direction we want to take, we can maybe uninstall `@antfu/ni` altogether from the project. I was not sure if it would break something so I did not touch it in this PR for now.

### CODE REVIEW

**Comment by prazdevs** [comment]
Not sure we should remove `ni`, nor push away from it. See https://github.com/nimbus-town/nimbus/issues/19#issuecomment-2495942360

**Comment by IonianPlayboy** [comment]
Closed in favor of #21

**Comment by IonianPlayboy** [comment]
After discussing it in #19, I have reopened this PR and will close #21 in favor of this one.

**Review by shuuji3 — APPROVED** [review]
Thanks for clearing up! It's clearer and less confusing now.

**Pull request merged**
